language: node_js
node_js:
  - "iojs"
  - "7"
 before_script:
      - 'export CHROME_BIN=chromium-browser'
script:
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
